### ISSUE TITLE
mob spawn crash

### ISSUE THREAD

**Issue by dodge1038** [JamesLeDolphin/dmadditions-116#12]
When spawning a Kantrofarri, the game just crashes, and since it spawns naturally, it crashes every time its rendered.

**Comment by dodge1038** [comment]
-1

**Comment by JamesLeDolphin** [comment]
Crash log file, found in .minecraft/crash-logs folder

**Comment by dodge1038** [comment]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Multiple entries with same key: RenderType[CompositeState[[texture[Optional[minecraft:textures/misc/enchanted_item_glint.png](blur=true, mipmap=false)], glint_transparency, diffuse_lighting[false], shade_model[flat], alpha[0.0], depth_test[==], cull[false], lightmap[false], overlay[false], fog, no_layering, main_target, glint_texturing, write_mask_state[writeColor=true, writeDepth=false], line_width[1.0]], outlineProperty=none]]=net.minecraft.client.renderer.BufferBuilder@792af176 and RenderType[CompositeState[[texture[Optional[minecraft:textures/misc/enchanted_item_glint.png](blur=true, mipmap=false)], glint_transparency, diffuse_lighting[false], shade_model[flat], alpha[0.0], depth_test[==], cull[false], lightmap[false], overlay[false], fog, no_layering, main_target, glint_texturing, write_mask_state[writeColor=true, writeDepth=false], line_width[1.0]], outlineProperty=none]]=net.minecraft.client.renderer.BufferBuilder@754591f2

**Comment by dodge1038** [comment]
is that right?

**Comment by JamesLeDolphin** [comment]
yes thats the one

**Comment by dodge1038** [comment]
alright

**Comment by dodge1038** [comment]
i had almost lost a really important world because of the entity loading in naturally

**Comment by JamesLeDolphin** [comment]
That doesnt appear to be caused by DMA, do you have any mods that affect rendering?

**Comment by dodge1038** [comment]
there was actually a different error message i was getting before, that one popped up and it was different, so i could try to get you the one i kept getting originally

**Comment by JamesLeDolphin** [comment]
best to just join the discord server and send the entire file

**Comment by dodge1038** [comment]
could you send me a link to it?

**Comment by dodge1038** [comment]
The game crashed whilst rendering entity in world
Error: java.lang.NullPointerException: Rendering entity in world

this is what i kept getting originally as the crash message on the launcher

**Comment by JamesLeDolphin** [comment]
https://discord.gg/48H8BW9G
